name = "Exercism"
uuid = "6c776c10-959d-11e8-058b-8f5b68a13ac9"
authors = ["Sascha Mann <git@mail.saschamann.eu>"]
version = "0.1.2"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
